/**
 * Source Types for OpenCitation
 */

export const SOURCE_TYPES = [
  // Print / long-form
  'book',
  'book-chapter',
  'journal',
  'newspaper',
  'website',
  'blog',
  // Audiovisual / performance
  'video',
  'film',
  'tv-series',
  'tv-episode',
  'song',
  'album',
  'podcast-episode',
  'video-game',
  // Visual / archival
  'image',
  'artwork',
  // Academic / research
  'thesis',
  'conference-paper',
  'dataset',
  'software',
  'preprint',
  // Modern / other
  'social-media',
  'ai-generated',
  'interview',
  'government-report',
  'legal-case',
  'encyclopedia',
  'miscellaneous',
] as const;

export type SourceType = (typeof SOURCE_TYPES)[number];

export const SOURCE_TYPE_LABELS: Record<SourceType, string> = {
  book: 'Book',
  'book-chapter': 'Book Chapter',
  journal: 'Academic Journal',
  newspaper: 'Newspaper',
  website: 'Website',
  blog: 'Blog',
  video: 'Video',
  film: 'Film',
  'tv-series': 'TV Series',
  'tv-episode': 'TV Episode',
  song: 'Song',
  album: 'Album',
  'podcast-episode': 'Podcast Episode',
  'video-game': 'Video Game',
  image: 'Image',
  artwork: 'Artwork',
  thesis: 'Thesis / Dissertation',
  'conference-paper': 'Conference Paper',
  dataset: 'Dataset',
  software: 'Software / Code',
  preprint: 'Preprint',
  'social-media': 'Social Media Post',
  'ai-generated': 'AI-Generated Content',
  interview: 'Interview',
  'government-report': 'Government Report',
  'legal-case': 'Legal Case',
  encyclopedia: 'Encyclopedia Entry',
  miscellaneous: 'Miscellaneous',
};

export const SOURCE_TYPE_DESCRIPTIONS: Record<SourceType, string> = {
  book: 'Physical and eBooks',
  'book-chapter': 'A chapter in an edited volume',
  journal: 'Peer-reviewed articles',
  newspaper: 'News articles',
  website: 'General web pages',
  blog: 'Blog posts and articles',
  video: 'YouTube, Vimeo, online video',
  film: 'Movies, documentaries',
  'tv-series': 'Television shows (whole series)',
  'tv-episode': 'Individual TV episodes',
  song: 'Songs and audio recordings',
  album: 'Full music albums',
  'podcast-episode': 'A single podcast episode',
  'video-game': 'Video games',
  image: 'Photographs, graphics',
  artwork: 'Paintings, sculptures, installations',
  thesis: 'Doctoral or master\u2019s thesis',
  'conference-paper': 'Papers presented at conferences',
  dataset: 'Research datasets',
  software: 'Code, libraries, applications',
  preprint: 'arXiv, bioRxiv, medRxiv, etc.',
  'social-media': 'Tweet / Post / Reel',
  'ai-generated': 'ChatGPT, Claude, Gemini, etc.',
  interview: 'Personal or published interviews',
  'government-report': 'Agency and policy documents',
  'legal-case': 'Court cases (simple citation, not Bluebook)',
  encyclopedia: 'Encyclopedia or dictionary entry',
  miscellaneous: 'Other sources',
};
